# Python version
FROM python:3.7-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update && apk add build-base postgresql-dev libffi-dev curl

# Copy files to working directory
RUN mkdir /code
COPY ./example /code/

# Install dependencies
WORKDIR /code
RUN pip install pipenv
RUN pipenv lock --clear
RUN pipenv install

CMD ["pipenv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]