{% extends "polaris.stellar.toml" %}

{% if CURRENCIES %}{% for c in CURRENCIES %}
[[CURRENCIES]]
code = "{{c.code}}"{% endif %}
code_template = "{{c.code}}"{% endif %}
issuer= "{{c.issuer}}"{% endif %}
status= "{{c.status}}"{% endif %}
display_decimals = "{{c.display_decimals}}"{% endif %}
{% endfor %}]{% endif %}
