# Generated by Django 2.2.8 on 2020-01-07 23:36

from django.db import migrations, models
from django.core.validators import MinLengthValidator
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("polaris", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolarisUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=254)),
                ("last_name", models.CharField(max_length=254)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PolarisStellarAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        max_length=56, unique=True, validators=[MinLengthValidator(56)]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.PolarisUser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolarisUserTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.PolarisStellarAccount",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polaris.Transaction",
                    ),
                ),
            ],
        ),
    ]
