# Generated by Django 3.2.8 on 2021-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_offchainassetextra"),
    ]

    operations = [
        migrations.AddField(
            model_name="polarisusertransaction",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="polarisusertransaction",
            name="requires_confirmation",
            field=models.BooleanField(default=False),
        ),
    ]
