# Generated by Django 2.2.3 on 2019-07-01 14:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('optional', models.BooleanField(default=False)),
                ('choices', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
                ('fields', models.ManyToManyField(to='info.InfoField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField(unique=True)),
                ('deposit_enabled', models.BooleanField(default=True)),
                ('deposit_fee_fixed', models.FloatField()),
                ('deposit_fee_percent', models.FloatField()),
                ('deposit_min_amount', models.FloatField()),
                ('deposit_max_amount', models.FloatField()),
                ('withdrawal_enabled', models.BooleanField(default=True)),
                ('withdrawal_fee_fixed', models.FloatField()),
                ('withdrawal_fee_percent', models.FloatField()),
                ('withdrawal_min_amount', models.FloatField()),
                ('withdrawal_max_amount', models.FloatField()),
                ('deposit_fields', models.ManyToManyField(to='info.InfoField')),
                ('withdrawal_types', models.ManyToManyField(related_name='withdrawal_info', to='info.WithdrawalType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
