# Generated by Django 2.2.4 on 2019-08-26 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20190726_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawaltype',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='deposit_fields',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='withdrawal_types',
        ),
        migrations.DeleteModel(
            name='InfoField',
        ),
        migrations.DeleteModel(
            name='WithdrawalType',
        ),
    ]
