# Generated by Django 2.2.4 on 2019-08-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("info", "0003_auto_20190826_2353")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="deposit_fee_fixed",
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="deposit_fee_percent",
            field=models.FloatField(blank=True, default=0.01),
        ),
        migrations.AlterField(
            model_name="asset",
            name="deposit_max_amount",
            field=models.FloatField(blank=True, default=10000.0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="deposit_min_amount",
            field=models.FloatField(blank=True, default=10.0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_fee_fixed",
            field=models.FloatField(blank=True, default=1.0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_fee_percent",
            field=models.FloatField(blank=True, default=0.01),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_max_amount",
            field=models.FloatField(blank=True, default=10000.0),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_min_amount",
            field=models.FloatField(blank=True, default=10.0),
        ),
    ]
