# Generated by Django 2.2.4 on 2019-10-14 23:30
# Manually modified to RenameField and add a setting as default

import django.core.validators
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [("info", "0004_auto_20190829_2106")]

    operations = [
        migrations.RenameField(model_name="asset", old_name="name", new_name="code"),
        migrations.AlterField(
            model_name="asset",
            name="code",
            field=models.TextField(
                default="USD", validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="issuer",
            field=models.TextField(
                default=settings.STELLAR_ISSUER_ACCOUNT_ADDRESS,
                validators=[django.core.validators.MinLengthValidator(56)],
            ),
        ),
    ]
