# Generated by Django 2.2.4 on 2019-08-15 16:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('transaction', '0001_initial'), ('transaction', '0002_auto_20190729_2236'), ('transaction', '0003_auto_20190812_1852')]

    initial = True

    dependencies = [
        ('info', '0002_auto_20190726_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stellar_account', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('kind', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], default='deposit', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending_external', 'pending_external'), ('pending_anchor', 'pending_anchor'), ('pending_stellar', 'pending_stellar'), ('pending_trust', 'pending_trust'), ('pending_user', 'pending_user'), ('pending_user_transfer_start', 'pending_user_transfer_start'), ('incomplete', 'incomplete'), ('no_market', 'no_market'), ('too_small', 'too_small'), ('too_large', 'too_large'), ('error', 'error')], default='pending_external', max_length=30)),
                ('status_eta', models.IntegerField(blank=True, null=True)),
                ('stellar_transaction_id', models.TextField(blank=True, null=True)),
                ('external_transaction_id', models.TextField(blank=True, null=True)),
                ('amount_in', models.FloatField(blank=True, null=True)),
                ('amount_out', models.FloatField(blank=True, null=True)),
                ('amount_fee', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Asset')),
                ('deposit_memo', models.TextField(blank=True, null=True)),
                ('deposit_memo_type', models.CharField(choices=[('text', 'text'), ('id', 'id'), ('hash', 'hash')], default='text', max_length=10)),
                ('external_extra', models.TextField(blank=True, null=True)),
                ('external_extra_text', models.TextField(blank=True, null=True)),
                ('from_address', models.TextField(blank=True, null=True)),
                ('to_address', models.TextField(blank=True, null=True)),
                ('withdraw_anchor_account', models.TextField(blank=True, null=True)),
                ('withdraw_memo', models.TextField(blank=True, null=True)),
                ('withdraw_memo_type', models.CharField(choices=[('text', 'text'), ('id', 'id'), ('hash', 'hash')], default='text', max_length=10)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
