# Generated by Django 2.2.4 on 2019-08-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_squashed_0003_auto_20190812_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status_eta',
            field=models.IntegerField(blank=True, default=3600, null=True),
        ),
    ]
