# Generated by Django 2.2.3 on 2019-07-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deposit_memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_memo_type',
            field=models.CharField(choices=[('text', 'text'), ('id', 'id'), ('hash', 'hash')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_extra_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_anchor_account',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_memo_type',
            field=models.CharField(choices=[('text', 'text'), ('id', 'id'), ('hash', 'hash')], default='text', max_length=10),
        ),
    ]
