title: Polaris Configuration Variables

django_debug: true
django_secret_key: "secretkeykeysecret"

assets:
  myusd:
    distribution_account_seed: "SBHSEGABIZI5HW75P2CEYVWLFNTMWTNRB7PGDA4SSMWTXCCQQGPKESJL"
    issuer_account_address: "GBH7AACZJUQBX4LN6NJP6HL3S6S3AAOIHNBQZHSSYOCCTSLEUQ54BTLG"

# STELLAR_NETWORK_PASSPHRASE can either be "Test SDF Network ; September 2015" or
# "Public Global Stellar Network ; September 2015" or a custom passphrase
# if you're using a private network.
stellar_network_passphrase: "Test SDF Network ; September 2015"

# HORIZON_URI can point to a custom Horizon URI. It currently points
# to the testnet URL.
horizon_uri: "https://horizon-testnet.stellar.org/"

secret_jwt_key: "secret"
