# Generated by Django 2.2.8 on 2020-01-13 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0003_auto_20191211_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="issuer",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(56)]
            ),
        ),
    ]
