# Generated by Django 2.2.9 on 2020-01-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0004_auto_20200113_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="significant_decimals",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="asset",
            name="deposit_fee_fixed",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=1.0, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="deposit_fee_percent",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=0.01, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="deposit_max_amount",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=10000.0, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="deposit_min_amount",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=10.0, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_fee_fixed",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=1.0, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_fee_percent",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=0.01, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_max_amount",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=10000.0, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="withdrawal_min_amount",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=10.0, max_digits=30
            ),
        ),
    ]
