# Generated by Django 2.2.17 on 2021-01-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0004_auto_20201120_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="account_memo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="account_memo_type",
            field=models.CharField(
                choices=[("text", "text"), ("id", "id"), ("hash", "hash")],
                max_length=10,
                null=True,
                blank=True,
            ),
        ),
    ]
