# Generated by Django 2.2.10 on 2020-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0006_auto_20200129_2323"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
    ]
