# Generated by Django 2.2.10 on 2020-02-25 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0007_transaction_refunded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="significant_decimals",
            field=models.IntegerField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
    ]
