# Generated by Django 2.2.10 on 2020-04-13 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0008_auto_20200225_1713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="started_at",
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
