# Generated by Django 2.2.10 on 2020-04-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0008_auto_20200225_1713"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="paging_token",
            field=models.TextField(null=True),
        ),
    ]
