# Generated by Django 2.2.12 on 2020-04-20 22:05

from django.db import migrations, models


def set_existing_assets(apps, schema_editor):
    Asset = apps.get_model("polaris", "Asset")
    Asset.objects.update(sep24_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0011_auto_20200429_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="sep24_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="asset",
            name="sep6_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_assets),
    ]
