# Generated by Django 2.2.12 on 2020-04-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0010_auto_20200413_2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="sep24_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="asset",
            name="sep6_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
