# Generated by Django 3.2.6 on 2021-09-16 22:04

from django.db import migrations, models
import django.db.models.deletion
import polaris.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0011_transaction_amount_expected'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_asset', models.TextField()),
                ('sell_asset', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OffChainAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.TextField()),
                ('identifier', models.TextField()),
                ('significant_decimals', models.IntegerField(default=2)),
                ('country_codes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sell_asset', models.TextField()),
                ('buy_asset', models.TextField()),
                ('sell_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('buy_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('price', models.DecimalField(decimal_places=7, default=0, max_digits=30)),
                ('expires_at', models.DateTimeField(default=polaris.models.utc_now)),
                ('sell_delivery_method', models.TextField(blank=True)),
                ('buy_delivery_method', models.TextField(blank=True)),
                ('country_code', models.TextField(blank=True)),
                ('requested_expire_after', models.DateTimeField(default=polaris.models.utc_now)),
            ],
        ),
        migrations.CreateModel(
            name='SellDeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaris.offchainasset')),
            ],
        ),
        migrations.CreateModel(
            name='BuyDeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaris.offchainasset')),
            ],
        ),
    ]
