# Generated by Django 2.2.12 on 2020-05-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0014_auto_20200512_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sep31_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
