# Generated by Django 2.2.12 on 2020-05-15 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0015_asset_sep31_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sep31_send_fee_fixed',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='sep31_send_fee_percent',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='asset',
            name='sep31_send_max_amount',
            field=models.DecimalField(blank=True, decimal_places=7, default=999999999999999999, max_digits=30),
        ),
        migrations.AddField(
            model_name='asset',
            name='sep31_send_min_amount',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=30),
        ),
    ]
