# Generated by Django 2.2.12 on 2020-05-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0015_asset_symbol'),
        ('polaris', '0016_auto_20200515_2256'),
    ]

    operations = [
    ]
