# Generated by Django 2.2.13 on 2020-07-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0017_data_merge_memo_and_receiver_columns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="deposit_memo", new_name="memo",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="deposit_memo_type",
            new_name="memo_type",
        ),
        migrations.RemoveField(model_name="transaction", name="send_memo",),
        migrations.RemoveField(model_name="transaction", name="send_memo_type",),
        migrations.RemoveField(model_name="transaction", name="withdraw_memo",),
        migrations.RemoveField(model_name="transaction", name="withdraw_memo_type",),
        migrations.RenameField(
            model_name="transaction",
            old_name="send_anchor_account",
            new_name="receiving_anchor_account",
        ),
        migrations.RemoveField(
            model_name="transaction", name="withdraw_anchor_account",
        ),
    ]
