# Generated by Django 2.2.12 on 2020-05-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0017_merge_20200519_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='protocol',
            field=models.CharField(choices=[('sep6', 'sep6'), ('sep24', 'sep24'), ('sep31', 'sep31')], max_length=5, null=True),
        ),
    ]
