# Generated by Django 2.2.12 on 2020-06-01 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import polaris.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polaris', '0018_auto_20200526_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEP31Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('paging_token', models.TextField(null=True)),
                ('stellar_account', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(choices=[('pending_sender', 'pending_sender'), ('pending_stellar', 'pending_stellar'), ('pending_info_update', 'pending_info_update'), ('pending_receiver', 'pending_receiver'), ('pending_external', 'pending_external'), ('completed', 'completed'), ('error', 'error')], default='pending_sender', max_length=30)),
                ('status_eta', models.IntegerField(blank=True, default=3600, null=True)),
                ('status_message', models.TextField(blank=True, null=True)),
                ('stellar_transaction_id', models.TextField(blank=True, null=True)),
                ('external_transaction_id', models.TextField(blank=True, null=True)),
                ('amount_in', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('amount_out', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('amount_fee', models.DecimalField(blank=True, decimal_places=7, max_digits=30, null=True)),
                ('started_at', models.DateTimeField(default=polaris.models.utc_now)),
                ('completed_at', models.DateTimeField(null=True)),
                ('stellar_account_id', models.TextField(validators=[django.core.validators.MinLengthValidator(56)])),
                ('stellar_memo', models.TextField(blank=True, null=True)),
                ('stellar_memo_type', models.CharField(choices=[('text', 'text'), ('id', 'id'), ('hash', 'hash')], default='text', max_length=10)),
                ('refunded', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polaris.Asset')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
