# Generated by Django 2.2.13 on 2020-07-29 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0018_auto_20200723_2232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="send_fee_fixed",
            field=models.DecimalField(
                blank=True, decimal_places=7, default=0, max_digits=30
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="send_fee_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                default=0,
                max_digits=30,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
