# Generated by Django 2.2.10 on 2020-04-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_auto_20200222_0003"),
    ]

    operations = [
        migrations.AddField(
            model_name="polarisuser",
            name="bank_account_number",
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="polarisuser",
            name="bank_number",
            field=models.CharField(max_length=254, null=True),
        ),
    ]
