# Generated by Django 3.2.8 on 2021-10-21 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polaris", "0013_auto_20211011_1956"),
        ("server", "0007_auto_20210921_2005"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffChainAssetExtra",
            fields=[
                (
                    "offchain_asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="polaris.offchainasset",
                    ),
                ),
                (
                    "fee_fixed",
                    models.DecimalField(decimal_places=7, default=0, max_digits=30),
                ),
                ("fee_percent", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
