ACCOUNTS = [{% for account in ACCOUNTS %}
    "{{account}},"
{% endfor %}]
VERSION = "{{VERSION}}"
SIGNING_KEY = "{{SIGNING_KEY}}"
NETWORK_PASSPHRASE = "{{NETWORK_PASSPHRASE}}"
{% if TRANSFER_SERVER %}TRANSFER_SERVER = "{{TRANSFER_SERVER}}"{% endif %}
{% if TRANSFER_SERVER_SEP0024 %}TRANSFER_SERVER_SEP0024 = "{{TRANSFER_SERVER_SEP0024}}"{% endif %}
{% if WEB_AUTH_ENDPOINT %}WEB_AUTH_ENDPOINT = "{{WEB_AUTH_ENDPOINT}}"{% endif %}
{% if KYC_SERVER %}KYC_SERVER = "{{KYC_SERVER}}"{% endif %}
{% if DIRECT_PAYMENT_SERVER %}DIRECT_PAYMENT_SERVER = "{{DIRECT_PAYMENT_SERVER}}"{% endif %}
